name: 'Get Required Files'
description: 'Checks manifest.json & creates a list of required files'

outputs:
  files:
    value: ${{ steps.get-files.outputs.files }}

runs:
  using: composite
  steps:
    - name: Get manifest items
      id: get-files
      run: |
        items=( $(jq -r '[ (.icons | map(.)), (.content_scripts[] | [.js, .css, .html] | flatten | map(select(. != null))), (.background.service_worker), (.web_accessible_resources[] | [.resources] | flatten | map(select(. != null))) ] | flatten | @sh' < manifest.json | xargs echo) )
        items=( $(for item in ${items[@]}; do echo $item | sed 's/\/.*//'; done) )
        files=$(sort -u <<<"$(printf '%s\n' ${items[@]})")
        echo files=$files >> "$GITHUB_OUTPUT"
