name: 'Validate Version'
description: 'Checks the uploaded version and makes sure the current version is above that'

runs:
  using: composite
  steps:
    - name: Get manifest items
      id: get-files
      run: |
        access_token=$(curl "https://oauth2.googleapis.com/token" -d "client_secret=$CLIENT_SECRET&grant_type=refresh_token&refresh_token=$REFRESH_TOKEN&client_id=$CLIENT_ID" | jq -r '.access_token')
        version=$(curl --location 'https://www.googleapis.com/chromewebstore/v1.1/items/'$EXTENSION_ID'?projection=DRAFT' --header "Authorization: Bearer $access_token" | jq -r '.crxVersion')
        echo "version=$version" >> "$GITHUB_OUTPUT"
